### ISSUE TITLE
@static files 500 every other time when fingerprint false

### ISSUE THREAD

**Issue by jessehattabaugh** [enhance-dev/arc-plugin-enhance#88]
I have an app which is deployed to API Gateway (no CloudFront) with Architect, and arc-plugin-enhance. In my .arc file I have:

```
@static
fingerprint false
```
When I load the page, the static files will load on every other request. (note commented out ServiceWorker registration)

For example, when I load https://schizo.social/_public/browser/async.mjs I first see:
![image](https://github.com/enhance-dev/arc-plugin-enhance/assets/17991/85bfe1a6-8541-40b4-a0a3-24f2b6273fed)

then I hit the reload button and see:
![image](https://github.com/enhance-dev/arc-plugin-enhance/assets/17991/94dd6ff9-6497-48fa-88b0-45a6e4c043ea)

reloading again, I see the file again

**Comment by ryanbethel** [comment]
@jessehattabaugh Can you create a reduced example we can use to reproduce it? I have tried but I can't reproduce it so far.

**Comment by jessehattabaugh** [comment]
@ryanbethel I added you as a collaborator. I followed these instructions when I set it up in AWS https://arc.codes/docs/en/guides/domains/registrars/route53

I get the same behavior if I use the raw API Gateway host https://133fgiavmb.execute-api.us-east-1.amazonaws.com/_public/browser/async.mjs

**Comment by jessehattabaugh** [comment]
I tested with Firefox and got the same behavior.

I then tested by opening the same file in two browsers, and alternating between them and it seems to alternate *per-browser* not *per-request*. Which makes me feel like it might have something to do with HTTP headers.

**Comment by jessehattabaugh** [comment]
If I disable the cache the behavior stops 
![image](https://github.com/enhance-dev/arc-plugin-enhance/assets/17991/782e013e-ba55-4b8b-bdd9-4362d0d3f5c5)

**Comment by ryanbethel** [comment]
@jessehattabaugh I think I have reproduced your bug. I think it is related to the cache control headers that are returned when fingerprinting is turned off. But I think it only happens after first deploying with fingerprinting turned on. And I think for it to happen `prune` has to be false. So that is as far as I will get tonight. I will verify this in the morning and see if I can track down the cause.

**Comment by ryanbethel** [comment]
@jessehattabaugh I found the bug and have a draft PR for a fix ([https://github.com/architect/asap/pull/417](https://github.com/architect/asap/pull/417)). I was slightly off in my comment above. It is caused by different error properties coming from the aws-sdk v3. I am going to get a couple more eyes on it before I can merge it, but I wanted to give you a heads-up.

**Comment by jessehattabaugh** [comment]
@ryanbethel you rock!

**Comment by ryanbethel** [comment]
No problem. The fix is published to the ASAP package. It should be in the enhance plugin today so you can update the plugin.
